### ISSUE TITLE
Overly large plugin icon

### ISSUE THREAD

**Issue by tmo26** [splitbrain/dokuwiki-plugin-searchindex#44]
Release 2018-04-22b "Greebo"

After updating to the latest version (2019-10-08) of the plugin, the plugin icon is displayed overly large:

![grafik](https://user-images.githubusercontent.com/12309103/67083759-073ad880-f19c-11e9-840e-e2ad53dc16f4.png)

For reference: We had the same issue before with the Batchedit plugin: https://github.com/dwp-forge/batchedit/issues/21#issuecomment-418618559

Same solution works also for the searchindex plugin.

**Comment by sysoftlab** [comment]
Sorry. I can not speak English very well. I rely on Google Translate.
There was a symptom of an icon appearing large on the screen because you did not specify the size in admin.svg.
I corrected it.
Please refer to this.
https://github.com/sysoftlab/dokuwiki-plugin-searchindex
The modified file is /lib/plugins/searchindex/**admin.svg**.
`
<svg xmlns = "http://www.w3.org/2000/svg" xmlns: xlink = "http://www.w3.org/1999/xlink" version = "1.1" width = "24" height = "24" viewBox = "0 0 24 24"> <path fill = "# 000000" d = "M15.5,12C18,12 20,14 20,16.5C20,17.38 19.75,18.21 19.31,18.9L22.39,22L21 , 23.39L17.88,20.32C17.19,20.75 16.37,21 15.5,21C13,21 11,19 11,16.5C11,14 13,12 15.5,12M15.5,14A2.5,2.5 0 0,0 13,16.5 A2.5,2.5 0 0,0 15.5,19 A2.5,2.5 0 0,0 18,16.5 A2.5,2.5 0 0,0 15.5,14M5,3H19C20.11,3 21,3.89 21,5V13.03C20. 5,12.23 19.81,11.54 19,11V5H5V19H9.5C9.81,19.75 10.26,20.42 10.81,21H5C3.89,21 3,20.11 3,19V5C3,3.89 3.89,3 5,3M7,7H17V9H7V7M7,11H12.03C11.23C11.54 , 12.19 10,13H7V11M7,15H9.17C9.06,15.5 9,16 9,16.5V17H7V15Z "/> </ svg>
`

**Comment by splitbrain** [comment]
The size of admin icons should be set by the template. I recommend opening a bug report for the template you use.

**Comment by gerardnico** [comment]
Wouah ... that was quick. Thanks.

**Comment by stanelie** [comment]
Thanks @sysoftlab , I corrected the admin.svg file with your fix and this solved the issue for me.

**Comment by tmo26** [comment]
Fixed by adding this to `_admin.css`:

```
/* size of icons in admin area */
.admin_plugins svg {
    width: 24px;
    height: 24px;
}
```
